openrndr.tasks=true
kotlin.code.style=official
#org.gradle.configuration-cache=true
#org.gradle.configuration-cache.parallel=true
#org.gradle.configuration-cache.problems=warn

# The Kotlin daemon runs out of heap on this project at its 512m default.
org.gradle.jvmargs=-Xmx3g
kotlin.daemon.jvmargs=-Xmx3g
